FROM node:21-alpine

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY . /app

# Install dependencies
RUN npm install

# Expose port 3000
EXPOSE 8080

# Start the application
CMD [ "npm", "start" ]

